-- Role-based permission matrix
-- Stores configurable feature access per role.
-- RLS is the security floor; this table controls UI/feature visibility on top.

CREATE TABLE IF NOT EXISTS role_permissions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  role text NOT NULL,
  feature_key text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  updated_at timestamptz DEFAULT now(),
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  UNIQUE(role, feature_key)
);

ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;

-- PM roles can read; only admin/pm can write
CREATE POLICY "pm_can_read_permissions" ON role_permissions
  FOR SELECT USING (get_my_role() IN ('pm', 'apm', 'super', 'admin'));

CREATE POLICY "pm_can_write_permissions" ON role_permissions
  FOR ALL USING (get_my_role() IN ('pm', 'admin'));

-- Seed defaults matching current hardcoded behavior
-- Format: (role, feature_key, enabled)
INSERT INTO role_permissions (role, feature_key, enabled) VALUES
-- ── PM (full access to all internal features) ──
('pm', 'tab.overview', true),
('pm', 'tab.jobs', true),
('pm', 'tab.residential', true),
('pm', 'tab.billing', true),
('pm', 'tab.orders', true),
('pm', 'tab.directory', true),
('pm', 'tab.nv_team', true),
('pm', 'tab.employees', true),
('pm', 'tab.vehicles', true),
('pm', 'tab.tools', true),
('pm', 'tab.estimator', true),
('pm', 'tab.bd', true),
('pm', 'tab.calendar', true),
('pm', 'jobdetail.labor', true),
('pm', 'billing.approve', true),
('pm', 'billing.mark_paid', true),
('pm', 'billing.delete_submission', true),
('pm', 'costs.approve', true),
('pm', 'costs.apm_auto_approve', true),
('pm', 'drawings.upload', true),
('pm', 'drawings.delete', true),
('pm', 'users.manage_roles', true),
('pm', 'users.invite_internal', true),
('pm', 'users.invite_subs', true),
('pm', 'admin.merge_companies', true),
('pm', 'admin.apm_bid_access', true),
('pm', 'admin.permissions', true),
('pm', 'submit.billing_tab', false),
('pm', 'submit.contracts_tab', false),
('pm', 'submit.bids_tab', false),
('pm', 'submit.docs_tab', false),
('pm', 'submit.rfis_tab', false),
('pm', 'submit.punch_tab', false),
('pm', 'submit.messages_tab', false),
('pm', 'submit.team_tab', false),

-- ── APM ──
('apm', 'tab.overview', true),
('apm', 'tab.jobs', true),
('apm', 'tab.residential', true),
('apm', 'tab.billing', true),
('apm', 'tab.orders', true),
('apm', 'tab.directory', true),
('apm', 'tab.nv_team', false),
('apm', 'tab.employees', false),
('apm', 'tab.vehicles', true),
('apm', 'tab.tools', true),
('apm', 'tab.estimator', true),
('apm', 'tab.bd', false),
('apm', 'tab.calendar', true),
('apm', 'jobdetail.labor', false),
('apm', 'billing.approve', true),
('apm', 'billing.mark_paid', true),
('apm', 'billing.delete_submission', true),
('apm', 'costs.approve', false),
('apm', 'costs.apm_auto_approve', false),
('apm', 'drawings.upload', true),
('apm', 'drawings.delete', true),
('apm', 'users.manage_roles', false),
('apm', 'users.invite_internal', false),
('apm', 'users.invite_subs', true),
('apm', 'admin.merge_companies', false),
('apm', 'admin.apm_bid_access', false),
('apm', 'admin.permissions', false),
('apm', 'submit.billing_tab', false),
('apm', 'submit.contracts_tab', false),
('apm', 'submit.bids_tab', false),
('apm', 'submit.docs_tab', false),
('apm', 'submit.rfis_tab', false),
('apm', 'submit.punch_tab', false),
('apm', 'submit.messages_tab', false),
('apm', 'submit.team_tab', false),

-- ── SUPER (superintendent — primary portal is /field, not dashboard) ──
('super', 'tab.overview', false),
('super', 'tab.jobs', false),
('super', 'tab.residential', false),
('super', 'tab.billing', false),
('super', 'tab.orders', false),
('super', 'tab.directory', false),
('super', 'tab.nv_team', false),
('super', 'tab.employees', false),
('super', 'tab.vehicles', false),
('super', 'tab.tools', false),
('super', 'tab.estimator', false),
('super', 'tab.bd', false),
('super', 'tab.calendar', false),
('super', 'jobdetail.labor', false),
('super', 'billing.approve', true),
('super', 'billing.mark_paid', true),
('super', 'billing.delete_submission', true),
('super', 'costs.approve', false),
('super', 'costs.apm_auto_approve', true),
('super', 'drawings.upload', true),
('super', 'drawings.delete', true),
('super', 'users.manage_roles', false),
('super', 'users.invite_internal', false),
('super', 'users.invite_subs', false),
('super', 'admin.merge_companies', false),
('super', 'admin.apm_bid_access', false),
('super', 'admin.permissions', false),
('super', 'submit.billing_tab', false),
('super', 'submit.contracts_tab', false),
('super', 'submit.bids_tab', false),
('super', 'submit.docs_tab', false),
('super', 'submit.rfis_tab', false),
('super', 'submit.punch_tab', false),
('super', 'submit.messages_tab', false),
('super', 'submit.team_tab', false),

-- ── ADMIN (office admin — primary portal is /admin) ──
('admin', 'tab.overview', true),
('admin', 'tab.jobs', true),
('admin', 'tab.residential', true),
('admin', 'tab.billing', true),
('admin', 'tab.orders', true),
('admin', 'tab.directory', true),
('admin', 'tab.nv_team', false),
('admin', 'tab.employees', false),
('admin', 'tab.vehicles', false),
('admin', 'tab.tools', false),
('admin', 'tab.estimator', true),
('admin', 'tab.bd', false),
('admin', 'tab.calendar', true),
('admin', 'jobdetail.labor', false),
('admin', 'billing.approve', true),
('admin', 'billing.mark_paid', true),
('admin', 'billing.delete_submission', true),
('admin', 'costs.approve', true),
('admin', 'costs.apm_auto_approve', true),
('admin', 'drawings.upload', false),
('admin', 'drawings.delete', false),
('admin', 'users.manage_roles', false),
('admin', 'users.invite_internal', false),
('admin', 'users.invite_subs', true),
('admin', 'admin.merge_companies', true),
('admin', 'admin.apm_bid_access', false),
('admin', 'admin.permissions', true),
('admin', 'submit.billing_tab', false),
('admin', 'submit.contracts_tab', false),
('admin', 'submit.bids_tab', false),
('admin', 'submit.docs_tab', false),
('admin', 'submit.rfis_tab', false),
('admin', 'submit.punch_tab', false),
('admin', 'submit.messages_tab', false),
('admin', 'submit.team_tab', false),

-- ── SUBCONTRACTOR ──
('subcontractor', 'tab.overview', false),
('subcontractor', 'tab.jobs', false),
('subcontractor', 'tab.residential', false),
('subcontractor', 'tab.billing', false),
('subcontractor', 'tab.orders', false),
('subcontractor', 'tab.directory', false),
('subcontractor', 'tab.nv_team', false),
('subcontractor', 'tab.employees', false),
('subcontractor', 'tab.vehicles', false),
('subcontractor', 'tab.tools', false),
('subcontractor', 'tab.estimator', false),
('subcontractor', 'tab.bd', false),
('subcontractor', 'tab.calendar', false),
('subcontractor', 'jobdetail.labor', false),
('subcontractor', 'billing.approve', false),
('subcontractor', 'billing.mark_paid', false),
('subcontractor', 'billing.delete_submission', false),
('subcontractor', 'costs.approve', false),
('subcontractor', 'costs.apm_auto_approve', false),
('subcontractor', 'drawings.upload', false),
('subcontractor', 'drawings.delete', false),
('subcontractor', 'users.manage_roles', false),
('subcontractor', 'users.invite_internal', false),
('subcontractor', 'users.invite_subs', false),
('subcontractor', 'admin.merge_companies', false),
('subcontractor', 'admin.apm_bid_access', false),
('subcontractor', 'admin.permissions', false),
('subcontractor', 'submit.billing_tab', true),
('subcontractor', 'submit.contracts_tab', true),
('subcontractor', 'submit.bids_tab', true),
('subcontractor', 'submit.docs_tab', true),
('subcontractor', 'submit.rfis_tab', true),
('subcontractor', 'submit.punch_tab', true),
('subcontractor', 'submit.messages_tab', true),
('subcontractor', 'submit.team_tab', false),

-- ── SUB_PM ──
('sub_pm', 'tab.overview', false),
('sub_pm', 'tab.jobs', false),
('sub_pm', 'tab.residential', false),
('sub_pm', 'tab.billing', false),
('sub_pm', 'tab.orders', false),
('sub_pm', 'tab.directory', false),
('sub_pm', 'tab.nv_team', false),
('sub_pm', 'tab.employees', false),
('sub_pm', 'tab.vehicles', false),
('sub_pm', 'tab.tools', false),
('sub_pm', 'tab.estimator', false),
('sub_pm', 'tab.bd', false),
('sub_pm', 'tab.calendar', false),
('sub_pm', 'jobdetail.labor', false),
('sub_pm', 'billing.approve', false),
('sub_pm', 'billing.mark_paid', false),
('sub_pm', 'billing.delete_submission', false),
('sub_pm', 'costs.approve', false),
('sub_pm', 'costs.apm_auto_approve', false),
('sub_pm', 'drawings.upload', false),
('sub_pm', 'drawings.delete', false),
('sub_pm', 'users.manage_roles', false),
('sub_pm', 'users.invite_internal', false),
('sub_pm', 'users.invite_subs', false),
('sub_pm', 'admin.merge_companies', false),
('sub_pm', 'admin.apm_bid_access', false),
('sub_pm', 'admin.permissions', false),
('sub_pm', 'submit.billing_tab', true),
('sub_pm', 'submit.contracts_tab', true),
('sub_pm', 'submit.bids_tab', true),
('sub_pm', 'submit.docs_tab', true),
('sub_pm', 'submit.rfis_tab', true),
('sub_pm', 'submit.punch_tab', true),
('sub_pm', 'submit.messages_tab', true),
('sub_pm', 'submit.team_tab', true),

-- ── SUB_ADMIN ──
('sub_admin', 'tab.overview', false),
('sub_admin', 'tab.jobs', false),
('sub_admin', 'tab.residential', false),
('sub_admin', 'tab.billing', false),
('sub_admin', 'tab.orders', false),
('sub_admin', 'tab.directory', false),
('sub_admin', 'tab.nv_team', false),
('sub_admin', 'tab.employees', false),
('sub_admin', 'tab.vehicles', false),
('sub_admin', 'tab.tools', false),
('sub_admin', 'tab.estimator', false),
('sub_admin', 'tab.bd', false),
('sub_admin', 'tab.calendar', false),
('sub_admin', 'jobdetail.labor', false),
('sub_admin', 'billing.approve', false),
('sub_admin', 'billing.mark_paid', false),
('sub_admin', 'billing.delete_submission', false),
('sub_admin', 'costs.approve', false),
('sub_admin', 'costs.apm_auto_approve', false),
('sub_admin', 'drawings.upload', false),
('sub_admin', 'drawings.delete', false),
('sub_admin', 'users.manage_roles', false),
('sub_admin', 'users.invite_internal', false),
('sub_admin', 'users.invite_subs', false),
('sub_admin', 'admin.merge_companies', false),
('sub_admin', 'admin.apm_bid_access', false),
('sub_admin', 'admin.permissions', false),
('sub_admin', 'submit.billing_tab', true),
('sub_admin', 'submit.contracts_tab', true),
('sub_admin', 'submit.bids_tab', true),
('sub_admin', 'submit.docs_tab', true),
('sub_admin', 'submit.rfis_tab', true),
('sub_admin', 'submit.punch_tab', true),
('sub_admin', 'submit.messages_tab', true),
('sub_admin', 'submit.team_tab', true),

-- ── SUB_ESTIMATOR ──
('sub_estimator', 'tab.overview', false),
('sub_estimator', 'tab.jobs', false),
('sub_estimator', 'tab.residential', false),
('sub_estimator', 'tab.billing', false),
('sub_estimator', 'tab.orders', false),
('sub_estimator', 'tab.directory', false),
('sub_estimator', 'tab.nv_team', false),
('sub_estimator', 'tab.employees', false),
('sub_estimator', 'tab.vehicles', false),
('sub_estimator', 'tab.tools', false),
('sub_estimator', 'tab.estimator', false),
('sub_estimator', 'tab.bd', false),
('sub_estimator', 'tab.calendar', false),
('sub_estimator', 'jobdetail.labor', false),
('sub_estimator', 'billing.approve', false),
('sub_estimator', 'billing.mark_paid', false),
('sub_estimator', 'billing.delete_submission', false),
('sub_estimator', 'costs.approve', false),
('sub_estimator', 'costs.apm_auto_approve', false),
('sub_estimator', 'drawings.upload', false),
('sub_estimator', 'drawings.delete', false),
('sub_estimator', 'users.manage_roles', false),
('sub_estimator', 'users.invite_internal', false),
('sub_estimator', 'users.invite_subs', false),
('sub_estimator', 'admin.merge_companies', false),
('sub_estimator', 'admin.apm_bid_access', false),
('sub_estimator', 'admin.permissions', false),
('sub_estimator', 'submit.billing_tab', true),
('sub_estimator', 'submit.contracts_tab', true),
('sub_estimator', 'submit.bids_tab', true),
('sub_estimator', 'submit.docs_tab', true),
('sub_estimator', 'submit.rfis_tab', true),
('sub_estimator', 'submit.punch_tab', true),
('sub_estimator', 'submit.messages_tab', true),
('sub_estimator', 'submit.team_tab', false)

ON CONFLICT (role, feature_key) DO NOTHING;
